name: fuse-manager

# Controls when the action will run. Triggers the workflow on push request, or repository dispatch
on:
  repository_dispatch:
    type: [FUSE_Run]
jobs:
  build:
    name: FUSE_Run
    if: github.event.action == 'FUSE_Run'
    # if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment: fuse_env
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3.3.0
      - name: setup python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.10.10
      - name: setup cache
        uses: actions/cache@v3.2.6
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('fuse.py') }}-${{ hashFiles('requirements.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade requests
          pip install -r requirements.txt
          if [ -f requirements.txt ]; then pip install --upgrade --upgrade-strategy eager -r requirements.txt; fi
      - name: Run fuse-mgr.py # run file
        env:
          webex_bearer: ${{ secrets.ENV_WEBEX_BEARER }}
          person_email: ${{ github.event.client_payload.person_email }}
          auth_mgrs: ${{ secrets.auth_mgrs }}
          ts: ${{ github.event.client_payload.ts }}
          attachment: ${{ github.event.client_payload.attachment }}

        run: |
          python fuse-mgr.py