name: fuse-manager

# Controls when the action will run. Triggers the workflow on push request, or repository dispatch
on:
  repository_dispatch:
    type: [FUSE_Run]
jobs:
  build:
    name: Run fuse-mgr.py
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment: fuse_env
    steps:
      - name: repository dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: dirflash/Fuse
          client-payload: '{"attachment": "${{ github.attachment}}", "room-id": "${{ github.room-id }}", "room-type": "${{ github.room-type }}", "person_id": "${{ github.person_id }}", "person_email": "${{ github.person_email }}"}'
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.10
      - name: setup cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('fuse.py') }}-${{ hashFiles('requirements.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade requests
          pip install -r requirements.txt
          if [ -f requirements.txt ]; then pip install --upgrade --upgrade-strategy eager -r requirements.txt; fi
      - name: execute py script # run file
        env:
          webex_bearer: ${{ secrets.WEBEX_BEARER }}
          attachment: ${{ github.attachment }}
          room_id: ${{ github.room_id }}
          room_type: ${{ github.room_type }}
          person_id: ${{ github.person_id }}
          person_email: ${{ github.person_email }}
        run: |
          python fuse-mgr.py