name: fuse-mgr-response

# Controls when the action will run. Triggers the workflow on push request, or repository dispatch
on:
  repository_dispatch:
    type: [FUSE_MGR_RESPONSE]
jobs:
  build:
    name: FUSE_MGR_RESPONSE
    if: github.event.action == 'FUSE_MGR_RESPONSE'
    runs-on: ubuntu-latest
    environment: fuse_env
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3.3.0
      - name: setup python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.10.10
      - name: setup cache
        uses: actions/cache@v3.2.6
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('fuse.py') }}-${{ hashFiles('requirements.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade requests
          pip install -r requirements.txt
          if [ -f requirements.txt ]; then pip install --upgrade --upgrade-strategy eager -r requirements.txt; fi
      - name: Run fuse-mgr-respond.py
        env:
          webex_bearer: ${{ secrets.ENV_WEBEX_BEARER }}
          room_id: ${{ github.event.client_payload.room_id }}
          person_id: ${{ github.event.client_payload.person_id }}
          person_email: ${{ github.event.client_payload.person_email}}
          action: ${{ github.event.client_payload.action }}
          auth_mgrs: ${{ secrets.auth_mgrs }}
          attachment: ${{steps.downloads.outputs.attachment-artifact}}

          # webex_bearer: ${{ secrets.ENV_WEBEX_BEARER }}
          # ts: ${{ github.event.client_payload.ts }}
          # attachment: ${{ github.event.client_payload.attachment }}
          # room_id: ${{ github.event.client_payload.room_id }}
          # room_type: ${{ github.event.client_payload.room_type }}
          # person_id: ${{ github.event.client_payload.person_id }}
          # person_un: $${{ github.event.client_payload.person_un }}
          # person_display: $${{ github.event.client_payload.person_display }}
          # person_email: ${{ github.event.client_payload.person_email }}
          # auth_mgrs: ${{ secrets.auth_mgrs }}
          # MONGO_ADDR: ${{ vars.MONGO_ADDR }}
          # MONGO_DB : ${{ vars.MONGO_DB }}
          # BRIDGE_COLLECT : ${{ vars.BRIDGE_COLLECT }}
          # RESPONSE_COLLECT : ${{ vars.RESPONSE_COLLECT }}
          # MONGO_UN : ${{ secrets.MONGO_UN }}
          # MONGO_PW : ${{ secrets.MONGO_PW }}

        run: |
          python fuse-mgr-respond.py