name: fuse-mgr-response

# Controls when the action will run. Triggers the workflow on push request, or repository dispatch
on:
  repository_dispatch:
    type: [FUSE_SEND_SURVEYS]
jobs:
  build:
    name: FUSE_SEND_SURVEYS
    if: github.event.action == 'FUSE_SEND_SURVEYS'
    runs-on: ubuntu-latest
    environment: fuse_env
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3.3.0
      - name: setup python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.10.10
      - name: setup cache
        uses: actions/cache@v3.2.6
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('fuse.py') }}-${{ hashFiles('requirements.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade requests
          pip install -r requirements.txt
          if [ -f requirements.txt ]; then pip install --upgrade --upgrade-strategy eager -r requirements.txt; fi
      - name: Run fuse-mgr-respond.py
        env:
          webex_bearer: ${{ secrets.ENV_WEBEX_BEARER }}
          room_id: ${{ github.event.client_payload.room_id }}
          person_un: $${{ github.event.client_payload.person_un }}
          person_id: ${{ github.event.client_payload.person_id }}
          person_email: ${{ github.event.client_payload.person_email}}
          first_name: ${{ github.event.client_payload.first_name}}
          action: ${{ github.event.client_payload.action }}
          session_date: ${{ github.event.client_payload.session_date }}
          survey_url: ${{ github.event.client_payload.survey_url }}

        run: |
          python fuse_send_surveys.py