name: fuse-mgr-response

# Controls when the action will run. Triggers the workflow on push request, or repository dispatch
on:
  repository_dispatch:
    type: [FUSE_SEND_SURVEYS]
jobs:
  build:
    name: FUSE_SEND_SURVEYS
    if: github.event.action == 'FUSE_SEND_SURVEYS'
    runs-on: ubuntu-latest
    environment: fuse_env
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3.3.0
      - name: setup python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.10.10
      - name: setup cache
        uses: actions/cache@v3.2.6
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('fuse.py') }}-${{ hashFiles('requirements.txt') }}
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install --upgrade --upgrade-strategy eager -r requirements.txt; fi
      - name: Run fuse_send_surveys.py
        env:
          webex_bearer: ${{ secrets.ENV_WEBEX_BEARER }}
          person_id: ${{ github.event.client_payload.person_id }}
          first_name: ${{ github.event.client_payload.first_name }}
          action: ${{ github.event.client_payload.action }}
          session_date: ${{ github.event.client_payload.session_date }}
          survey_url: ${{ github.event.client_payload.survey_url }}
          mongo_id: ${{ github.event.client_payload.mongo_id }}
          MONGO_ADDR: ${{ vars.MONGO_ADDR }}
          MONGO_DB : ${{ vars.MONGO_DB }}
          MONGO_UN : ${{ secrets.MONGO_UN }}
          MONGO_PW : ${{ secrets.MONGO_PW }}
          SURVEY_COLLECT: ${{ vars.SURVEY_COLLECT }}

        run: |
          python fuse_send_surveys.py